os: linux
arch: arm64-graviton2
language: php
env:
  global:
    - DRUPAL_VERSION=7.x
  jobs:
    - TESTS=Actions,AJAX,Book,Bootstrap,Cache,Color,Comment,Contextual,Dashboard,DBLog,File,Filter,Forum,Help,Locale,Mail
    - TESTS=Pager,Path,PHP,Poll,RDF,Session,Shortcut,Syslog,Trigger,XML-RPC
    - TESTS=Aggregator,Block,Contact,Database,Image,OpenID,Menu,Node,Search
    - TESTS=Statistics,SimpleTest,System,Taxonomy,Theme
    - TESTS=Tracker,Translation,Update,User TESTS_WITH_SPACES="Entity API,Batch API,Field API,Field types,Field UI,File API,File API (remote),Form API,Path API"
matrix:
  allow_failures:
    - env: TESTS=Aggregator,Block,Contact,Database,Image,OpenID,Menu,Node,Search
    - env: TESTS=Statistics,SimpleTest,System,Taxonomy,Theme
    - env: TESTS=Translation,Update,User TESTS_WITH_SPACES="Entity API,Batch API,Field API,Field types,Field UI,File API,File API (remote),Form API,Path API"
php:
  - '7.4'
before_install:
  - cd ..
  - git clone https://git.drupalcode.org/project/DrupalSqlSrvCI.git DrupalCI
  - git clone https://git.drupalcode.org/issue/sqlsrv-3215864.git -b 7.x-2.x sqlsrv
install:
  - bash DrupalCI/src/travis/install.sh
  - export PATH="/opt/mssql-tools/bin:$PATH"
before_script:
  - bash DrupalCI/src/travis/build.sh
  - cd drupal-project
 # - phpenv config-add ../sqlsrv/dev/travis/travis-7.x.ini
  - rm -rf sites/all/modules/sqlsrv
  - rm -rf includes/database/sqlsrv
  - cp -R ../sqlsrv sites/all/modules/sqlsrv
  - cp -R ../sqlsrv/sqlsrv includes/database/sqlsrv
  - echo $TESTS_WITH_SPACES
script:
  - php ./scripts/run-tests.sh --verbose --fail-only --php `which php` $TESTS
