os: linux
arch: arm64-graviton2
language: php
env:
  global:
    - DRUPAL_VERSION=7.x
  jobs:
    - TESTS="Actions,AJAX,Batch API,Book,Bootstrap,Cache,Color,Comment,Contextual,Dashboard,DBLog,Entity API,Field API,Field types,Field UI"
    - TESTS="File,File API,File API (remote),Filter,Form API,Forum,Help,Locale,Mail,Pager,Path,Path API,PHP,Poll,RDF,Session,Shortcut,Syslog"
    - TESTS="Tracker,Translation,Trigger,XML-RPC"
    - TESTS=Aggregator,Block,Contact,Database,Image,OpenID,Menu,Node,User
    - TESTS=Search,Statistics,SimpleTest,System,Taxonomy,Theme,Update
matrix:
  allow_failures:
    - env: TESTS=Aggregator,Block,Contact,Database,Image,OpenID,Menu,Node,User
    - env: TESTS=Search,Statistics,SimpleTest,System,Taxonomy,Theme,Update
php:
  - '7.4'
before_install:
  - cd ..
  - git clone https://git.drupalcode.org/project/DrupalSqlSrvCI.git DrupalCI
  #- git clone https://git.drupalcode.org/project/sqlsrv.git -b 7.x-2.x sqlsrv
install:
  - bash DrupalCI/src/travis/install.sh
  - export PATH="/opt/mssql-tools/bin:$PATH"
before_script:
  - bash DrupalCI/src/travis/build.sh
  - cd drupal-project
 # - phpenv config-add ../sqlsrv/dev/travis/travis-7.x.ini
  #- rm -rf sites/all/modules/sqlsrv
  #- rm -rf includes/database/sqlsrv
  #- cp -R ../sqlsrv sites/all/modules/sqlsrv
  #- cp -R ../sqlsrv/sqlsrv includes/database/sqlsrv
script:
  - php ./scripts/run-tests.sh --concurrency 3 --verbose --fail-only --php `which php` "$TESTS"
